#!/bin/sh -x

alias matlab='LD_PRELOAD=/opt/gcc-4.8.1/lib64/libstdc++.so /opt/matlab/R2013a/bin/matlab'
alias ce="pushd ~/working/esp/branches/Pj119_reconstruction_p3"
alias cu="pushd /media/ANDREAS\ USB"
alias cr='pushd ~/running'
alias w='pushd ~/tb'
alias ld8='LD_LIBRARY_PATH=/opt/gcc-4.8.1/lib64:$LD_LIBRARY_PATH '
