#!/bin/bash
alias winter="ssh wintermute.sr.elekta.se"
alias w='pushd ~/working'
alias rebase='git svn rebase'
alias dcommit='git svn dcommit'
alias vi='vim'

# Don't set colorscheme as it is set by Windows wezterm
#~/dotfiles/ir_black_mintty.sh

platform=`uname`
if [[ $platform == CYGWIN* ]]; then
	export TERM=cygwin
fi

source ~/dotfiles/common_startup_work
