#!/bin/sh

function parse_git_branch {
    git rev-parse --git-dir > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        git_status="$(git status 2> /dev/null)"
        branch_pattern="^# On branch ([^${IFS}]*)"
        detached_branch_pattern="# Not currently on any branch"
        remote_pattern="# Your branch is (.*) of"
        diverge_pattern="# Your branch and (.*) have diverged"
        untracked_pattern="# Untracked files:"
        new_pattern="new file:"
        not_staged_pattern="Changes not staged for commit"

        #files not staged for commit
        if [[ ${git_status}} =~ ${not_staged_pattern} ]]; then
            state="✔"
        fi
        # add an else if or two here if you want to get more specific
        # show if we're ahead or behind HEAD
        if [[ ${git_status} =~ ${remote_pattern} ]]; then
            if [[ ${BASH_REMATCH[1]} == "ahead" ]]; then
                remote="↑"
            else
                remote="↓"
            fi
        fi
        #new files
        if [[ ${git_status} =~ ${new_pattern} ]]; then
            remote="+"
        fi
        #untracked files
        if [[ ${git_status} =~ ${untracked_pattern} ]]; then
            remote="✖"
        fi
        #diverged branch
        if [[ ${git_status} =~ ${diverge_pattern} ]]; then
            remote="↕"
        fi
        #branch name
        if [[ ${git_status} =~ ${branch_pattern} ]]; then
            branch=${BASH_REMATCH[1]}
        #detached branch
        elif [[ ${git_status} =~ ${detached_branch_pattern} ]]; then
            branch="NO BRANCH"
        fi

        echo "(${branch}${state}${remote})"
    fi
    return
}

green="\[\e[32m\]"
bold="\[\e[1m\]"
reset="\[\e[0m\]"
# export PS1="\h:\w\$(parse_git_branch)$ "
export PS1="\h:\W $green$bold$ $reset"

export CLICOLOR=1
export EDITOR='vim'

# Common aliases
alias m='make'
alias ta='tmux attach'
alias v='nvim'
alias ci='git ci'
alias co='git co'
alias f='fg'
alias l='ls'
alias s='git s'
#alias su='git s -uno'
alias g='git'
alias a='git add'
alias ap='git add -p'
alias AMEND='git ci --amend -C HEAD'
alias gsr='git svn rebase'
alias grc='git rebase --continue'
alias gmt='git mergetool'
alias ..="cd .."
alias ...="cd ../.."
alias .3="cd ../../.."
alias .4="cd ../../../.."
alias ch="pushd ~"
alias cw="pushd ~/working"
alias cdo="pushd ~/dotfiles"
alias pd="pushd"
alias cpr="cp -r"
alias gl=pretty_git_log
alias resource="source ~/dotfiles/common_startup"

export SVN_MERGE=~/dotfiles/svn_vimdiff_wrapper.sh

. ~/dotfiles/.githelpers

# Determine home/work based on domain
DN=$(dnsdomainname)

# Source home startup file
if [[ "$DN" == *.home ]]; then
  . ~/dotfiles/common_interactive_home
fi

# Source elekta startup file
if [[ "$DN" == *.elekta.com ]]; then
  . ~/dotfiles/common_interactive_elekta
fi

# Source host specific startup file
HOST_INTERACTIVE="$HOME/dotfiles/common_interactive_$(hostname)"
if [[ -f "$HOST_INTERACTIVE" ]]; then
  . "$HOST_INTERACTIVE"
fi
