#!/bin/sh

export CLICOLOR=1
export EDITOR='vim'

# Common aliases
alias ci='git ci'
alias co='git co'
alias f='fg'
alias l='ls'
alias s='git s'
alias su='git s -uno'
alias g='git'
alias a='git add'
alias ap='git add -p'
alias AMEND='git ci --amend -C HEAD'
alias ..="cd .."
alias ...="cd ../.."
alias .3="cd ../../.."
alias .4="cd ../../../.."

# Source host specific startup file
DIRNAME="$( cd "$( dirname "$0" )" && pwd )"
. "$DIRNAME"/common_startup_`hostname`
